// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxdlozhjhcxgcerjwrnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4ZGxvemhqaGN4Z2Nlcmp3cm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDQzOTYsImV4cCI6MjA2MTY4MDM5Nn0.sBhFCFkHjs2Qd7msM-AEUtn8JnI4VYCHtm_DDofFIf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);